#! /bin/sh

sxhkd &
compton &
dunst &

$HOME/.config/polybar/launch.sh

#bspc monitor -d I II III IV V VI VII VIII IX X
$HOME/.config/bspwm/monitor-script.sh
bspc config external_rules_command $HOME/.config/bspwm/external-rules.sh


bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config focused_border_color "#EBB4CB"
bspc config focused_border_color "#00FFFF"
bspc config normal_border_color "#2f343f"


# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# wal -i img.jpg -n
# wal -i "$(< "${HOME}/.cache/wal/wal")"
# feh --bg-scale "$(< "${HOME}/.cache/wal/wal")"

